### ISSUE TITLE
Notebook plugin tasks

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#320]
The following are tasks related to the notebook plugin tasks we aim to complete by SciPy 2016.

- [x] J/K keyboard shortcuts in notebook
- [ ] Fix code cell font alignment (@ellisonbg) - See #698
- [x] .rendered_html CSS (@ellisonbg)  Fixed by #706
- [x] L/R/B border
- [x] 13px UI font
- [ ] MD icons in toolbar - see #686 for further discussion
- [x] Add notebook menu

**Comment by eskirk** [comment]
Also, general style things such as #300

**Comment by spoorthyv** [comment]
Also, add kernel switcher dialog when you click on the label on the top right of the notebook.

**Comment by faricacarroll** [comment]
hey @ellisonbg, when you have time could we get help on how to add MD icons in the toolbar?

thanks!

**Comment by blink1073** [comment]
Should we add some padding to the toolbar to avoid this overlap?

<img width="139" alt="screen shot 2016-07-13 at 8 47 44 am" src="https://cloud.githubusercontent.com/assets/2096628/16805593/85486afc-48d6-11e6-970a-b62d9210638e.png">

**Comment by jasongrout** [comment]
What's the status on this? Work in progress?

**Comment by jasongrout** [comment]
> Should we add some padding to the toolbar to avoid this overlap?

I think this is done, at least on one side:

![screen shot 2016-08-24 at 3 54 04 pm](https://cloud.githubusercontent.com/assets/192614/17945716/066e8d16-6a13-11e6-9f3a-4f5c196efaed.png)

**Comment by jasongrout** [comment]
> Fix code cell font alignment (@ellisonbg)
>  .rendered_html CSS (@ellisonbg)

@ellisonbg - I'm not sure what these tasks are. Are they done? If not, let's open specific issues for each one.

**Comment by blink1073** [comment]
Closing as all issues have been addressed or are tracked elsewhere (with links in the original comment).
